FROM amd64/ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y git
RUN cd $HOME && git clone https://github.com/k-ota106/dotfiles
RUN cd $HOME/dotfiles && bash ./bin/install.sh all

