# Register for lazy loaded denops plugin.

################################ fzf motion in the current window
[[plugins]]
 repo = 'yuki-yano/fuzzy-motion.vim'
 depends = ['denops.vim']
 hook_add = '''
 nnoremap <silent> <leader>o :FuzzyMotion<CR>
'''

################################ Execute current buffer 
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\    'verilog_systemverilog': {
\      'command': 'verilint.sh',
\    },
\    'tcl': {
\      'command': 'tclsh',
\    },
\   'c' : {
\       'cmdopt' : '-lm',
\    },
\   'cpp' : {
\       'cmdopt' : '-std=c++11',
\    },
\ }
'''

#################################### markdown
[[plugins]]
 repo = 'previm/previm'

[[plugins]]
 repo = 'tyru/open-browser.vim'
 on_map = ['<Plug>(openbrowser-smart-search)']
 
[[plugins]]
 repo = 'mzlogin/vim-markdown-toc'
 on_ft = 'markdown'

[[plugins]]
 repo = 'plasticboy/vim-markdown'
 on_ft = 'markdown'
 hook_add = '''
 let g:vim_markdown_toc_autofit = 0
 "let g:vim_markdown_folding_level = 6
 let g:vim_markdown_folding_disabled = 1
 set foldlevel=6
'''

